version: '3'
services:
  merchant:
    build: .
    container_name: mymerchant
    image: mymerchant:v1
    ports:
      - 3000:3000
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mysql:8.0.22
    container_name: merchant_mysql
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=task
    volumes:
      - $PWD/data:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - 3306:3306
    restart: always
